// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: guiton

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Arc1;
lv_obj_t * ui_time;
lv_obj_t * ui_ImgButton1;
lv_obj_t * ui_ikea;
lv_obj_t * ui_svetlo3;
lv_obj_t * ui_svetlo2;
lv_obj_t * ui_svetlo1;
lv_obj_t * ui_acbuttonOFF;
lv_obj_t * ui_acbutton;
lv_obj_t * ui_AC1label;
lv_obj_t * ui_AC1label2;
lv_obj_t * ui_SvaSvetla;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_temp;
// CUSTOM VARIABLES
lv_obj_t * uic_Arc1;
lv_obj_t * uic_time;
lv_obj_t * uic_Button1;
lv_obj_t * uic_ikea;
lv_obj_t * uic_svetlo3;
lv_obj_t * uic_svetlo2;
lv_obj_t * uic_svetlo1;
lv_obj_t * uic_acbuttonOFF;
lv_obj_t * uic_acbutton;
lv_obj_t * uic_AC1label;
lv_obj_t * uic_AC1label2;
lv_obj_t * uic_SvaSvetla;
lv_obj_t * uic_temp;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
