// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: guiton

#ifndef _GUITON_UI_H
#define _GUITON_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_ikea;
extern lv_obj_t * ui_svetlo3;
extern lv_obj_t * ui_svetlo2;
extern lv_obj_t * ui_svetlo1;
extern lv_obj_t * ui_acbuttonOFF;
extern lv_obj_t * ui_acbutton;
extern lv_obj_t * ui_AC1label;
extern lv_obj_t * ui_AC1label2;
extern lv_obj_t * ui_SvaSvetla;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_temp;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Arc1;
extern lv_obj_t * uic_time;
extern lv_obj_t * uic_Button1;
extern lv_obj_t * uic_ikea;
extern lv_obj_t * uic_svetlo3;
extern lv_obj_t * uic_svetlo2;
extern lv_obj_t * uic_svetlo1;
extern lv_obj_t * uic_acbuttonOFF;
extern lv_obj_t * uic_acbutton;
extern lv_obj_t * uic_AC1label;
extern lv_obj_t * uic_AC1label2;
extern lv_obj_t * uic_SvaSvetla;
extern lv_obj_t * uic_temp;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1259666894);    // assets/bg1 (2).png
LV_IMG_DECLARE(ui_img_dial1_png);    // assets/dial1.png
LV_IMG_DECLARE(ui_img_sv3b_png);    // assets/SV3B.png
LV_IMG_DECLARE(ui_img_sv3_png);    // assets/SV3.png
LV_IMG_DECLARE(ui_img_sv5b_png);    // assets/SV5B.png
LV_IMG_DECLARE(ui_img_sv5_png);    // assets/SV5.png
LV_IMG_DECLARE(ui_img_sv4b_png);    // assets/SV4B.png
LV_IMG_DECLARE(ui_img_sv4_png);    // assets/SV4.png
LV_IMG_DECLARE(ui_img_sv2b_png);    // assets/SV2B.png
LV_IMG_DECLARE(ui_img_sv2_png);    // assets/SV2.png
LV_IMG_DECLARE(ui_img_sv1b_png);    // assets/SV1B.png
LV_IMG_DECLARE(ui_img_sv1_png);    // assets/SV1.png
LV_IMG_DECLARE(ui_img_ac_png);    // assets/AC.png
LV_IMG_DECLARE(ui_img_acoff_png);    // assets/ACoff.png
LV_IMG_DECLARE(ui_img_sijalicasm_png);    // assets/sijalicasm.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
