// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: guiton

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_1259666894);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 500);

    ui_Arc1 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc1, 340);
    lv_obj_set_height(ui_Arc1, 340);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 50);
    lv_arc_set_bg_angles(ui_Arc1, 185, 0);
    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xADADBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Arc1, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_Arc1, &ui_img_dial1_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 0);
    lv_obj_set_y(ui_time, -49);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "22.45");
    lv_obj_set_style_text_font(ui_time, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton1 = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_sv3b_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_sv3_png, NULL);
    lv_obj_set_width(ui_ImgButton1, 45);
    lv_obj_set_height(ui_ImgButton1, 81);
    lv_obj_set_x(ui_ImgButton1, 0);
    lv_obj_set_y(ui_ImgButton1, 281);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ImgButton1, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_ImgButton1, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);      /// Flags

    ui_ikea = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_ikea, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_sv5b_png, NULL);
    lv_imgbtn_set_src(ui_ikea, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_sv5_png, NULL);
    lv_obj_set_width(ui_ikea, 43);
    lv_obj_set_height(ui_ikea, 79);
    lv_obj_set_x(ui_ikea, 114);
    lv_obj_set_y(ui_ikea, 86);
    lv_obj_set_align(ui_ikea, LV_ALIGN_CENTER);

    ui_svetlo3 = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_svetlo3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_sv4b_png, NULL);
    lv_imgbtn_set_src(ui_svetlo3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_sv4_png, NULL);
    lv_obj_set_width(ui_svetlo3, 48);
    lv_obj_set_height(ui_svetlo3, 73);
    lv_obj_set_x(ui_svetlo3, 59);
    lv_obj_set_y(ui_svetlo3, 120);
    lv_obj_set_align(ui_svetlo3, LV_ALIGN_CENTER);

    ui_svetlo2 = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_svetlo2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_sv2b_png, NULL);
    lv_imgbtn_set_src(ui_svetlo2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_sv2_png, NULL);
    lv_obj_set_width(ui_svetlo2, 47);
    lv_obj_set_height(ui_svetlo2, 74);
    lv_obj_set_x(ui_svetlo2, -59);
    lv_obj_set_y(ui_svetlo2, 124);
    lv_obj_set_align(ui_svetlo2, LV_ALIGN_CENTER);

    ui_svetlo1 = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_svetlo1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_sv1b_png, NULL);
    lv_imgbtn_set_src(ui_svetlo1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_sv1_png, NULL);
    lv_obj_set_width(ui_svetlo1, 45);
    lv_obj_set_height(ui_svetlo1, 74);
    lv_obj_set_x(ui_svetlo1, -114);
    lv_obj_set_y(ui_svetlo1, 86);
    lv_obj_set_align(ui_svetlo1, LV_ALIGN_CENTER);

    ui_acbuttonOFF = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_acbuttonOFF, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_ac_png, NULL);
    lv_imgbtn_set_src(ui_acbuttonOFF, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_acoff_png, NULL);
    lv_obj_set_width(ui_acbuttonOFF, 75);
    lv_obj_set_height(ui_acbuttonOFF, 27);
    lv_obj_set_x(ui_acbuttonOFF, 93);
    lv_obj_set_y(ui_acbuttonOFF, 19);
    lv_obj_set_align(ui_acbuttonOFF, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_acbuttonOFF, LV_STATE_PRESSED);       /// States

    ui_acbutton = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_acbutton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_ac_png, NULL);
    lv_imgbtn_set_src(ui_acbutton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_acoff_png, NULL);
    lv_imgbtn_set_src(ui_acbutton, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_ac_png, NULL);
    lv_imgbtn_set_src(ui_acbutton, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_ac_png, NULL);
    lv_obj_set_width(ui_acbutton, 75);
    lv_obj_set_height(ui_acbutton, 27);
    lv_obj_set_x(ui_acbutton, -93);
    lv_obj_set_y(ui_acbutton, 19);
    lv_obj_set_align(ui_acbutton, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_acbutton, LV_STATE_PRESSED);       /// States
    lv_obj_add_flag(ui_acbutton, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_AC1label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AC1label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AC1label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AC1label, -155);
    lv_obj_set_y(ui_AC1label, 18);
    lv_obj_set_align(ui_AC1label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AC1label, "ON");

    ui_AC1label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AC1label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AC1label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AC1label2, 155);
    lv_obj_set_y(ui_AC1label2, 18);
    lv_obj_set_align(ui_AC1label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AC1label2, "ON");

    ui_SvaSvetla = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_SvaSvetla, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_sijalicasm_png, NULL);
    lv_imgbtn_set_src(ui_SvaSvetla, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_sijalicasm_png, NULL);
    lv_obj_set_width(ui_SvaSvetla, 55);
    lv_obj_set_height(ui_SvaSvetla, 85);
    lv_obj_set_x(ui_SvaSvetla, 0);
    lv_obj_set_y(ui_SvaSvetla, 36);
    lv_obj_set_align(ui_SvaSvetla, LV_ALIGN_CENTER);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -111);
    lv_obj_set_y(ui_Label1, -5);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "stan");

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 116);
    lv_obj_set_y(ui_Label2, -5);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "lab");

    ui_temp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp, 0);
    lv_obj_set_y(ui_temp, -106);
    lv_obj_set_align(ui_temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp, "25.6c");
    lv_obj_set_style_text_font(ui_temp, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Arc1 = ui_Arc1;
    uic_time = ui_time;
    uic_Button1 = ui_ImgButton1;
    uic_ikea = ui_ikea;
    uic_svetlo3 = ui_svetlo3;
    uic_svetlo2 = ui_svetlo2;
    uic_svetlo1 = ui_svetlo1;
    uic_acbuttonOFF = ui_acbuttonOFF;
    uic_acbutton = ui_acbutton;
    uic_AC1label = ui_AC1label;
    uic_AC1label2 = ui_AC1label2;
    uic_SvaSvetla = ui_SvaSvetla;
    uic_temp = ui_temp;

}
